services:
  - type: redis
    name: Phaybin-Portfolio-redis
    region: Frankfurt
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: web
    name: Phaybin-Portfolio
    env: ruby
    region: Frankfurt
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: Phaybin-Portfolio-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false